### ISSUE TITLE
Is there a collection-equivalent assertion?

### ISSUE THREAD

**Issue by mgroves** [erichexter/Should#5]
I have two collections of strings (say, a ```string[] of "A","B","C"```, and a ```List<string> of "C","A","B"```), and I want to assert that these collections contain the same strings. Is there a Should extension for that that I'm missing?

**Comment by rogersillito** [comment]
I actually find myself doing this kind of assertion a lot, and use a workaround similar to the one you've suggested - but it would be nice to have this built in.  I was thinking along these lines:
    
    var list = new List<object>();
    var expected = new[] {1,2,3};
    list.Should().EqualSequence(expected); // Fails
    list.ShouldEqualSequence(expected);  // Fails
 
I'd be happy to work on an implementation for this; do you see this addition as a good fit for the project - and if so - agree with the approach?

**Comment by erichexter** [comment]
Yes, I think that looks reasonable.

**Comment by rogersillito** [comment]
Ok I'll get to work..
