### ISSUE TITLE
Should library should not throw exceptions

### ISSUE THREAD

**Issue by CodingYoshi** [erichexter/Should#7]
A simple test such as:
     true.ShouldBeFalse();
will result in an exception. Sure the test will fail but many frameworks such as NUnit will consider this an "Error" in test and not a "Failure". Why? Because the exception is being thrown as Should.Core.Exceptions.FalseException.

This needs to be addressed quickly, I think, since many frameworks and people use the Should library.

**Comment by erichexter** [comment]
So, the reason I throw exceptions is because the author of nunit and xunit told me to do that, is really the only way to communicate to the test framework that an assertion failed. Do you have an alternative implementation ?

**Comment by erichexter** [comment]
@CodingYoshi did you have any other feedback on this issue?  If not i will close it at the end of this week.

**Comment by sriv** [comment]
As one of the authors of another test-runner, [Gauge](http://getgauge.io), which has support for [C#](https://github.com/getgauge/gauge-csharp), I agree with the opinions authors of other test runners. I believe assertion frameworks throwing an exception makes it easier to report back assertion failures.
